// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtLomnAFrzb65O-mb5GslS1_Vq6X_bmrI',
    appId: '1:632692669439:web:dcd050726ff29c660e45ca',
    messagingSenderId: '632692669439',
    projectId: 'hobbybuddy-be26c',
    authDomain: 'hobbybuddy-be26c.firebaseapp.com',
    storageBucket: 'hobbybuddy-be26c.appspot.com',
    measurementId: 'G-TZJZF6D558',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnSyS_UX6ws9X9IkgF3mXs2qBVoWe88Tw',
    appId: '1:632692669439:android:00566ac71e3cbdf40e45ca',
    messagingSenderId: '632692669439',
    projectId: 'hobbybuddy-be26c',
    storageBucket: 'hobbybuddy-be26c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDguvnW8Wb9cWMy1EprOaAWHeG5H0vR-O4',
    appId: '1:632692669439:ios:f30f545fc9364c570e45ca',
    messagingSenderId: '632692669439',
    projectId: 'hobbybuddy-be26c',
    storageBucket: 'hobbybuddy-be26c.appspot.com',
    iosClientId: '632692669439-60rolqmbgvvpi4iqsciusoai1j1ohp4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.hobbybuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDguvnW8Wb9cWMy1EprOaAWHeG5H0vR-O4',
    appId: '1:632692669439:ios:f30f545fc9364c570e45ca',
    messagingSenderId: '632692669439',
    projectId: 'hobbybuddy-be26c',
    storageBucket: 'hobbybuddy-be26c.appspot.com',
    iosClientId: '632692669439-60rolqmbgvvpi4iqsciusoai1j1ohp4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.hobbybuddy',
  );
}
